"""RedTask project_id and VehicleMoveWithoutTask table

Revision ID: 1ea0e6a19990
Revises: e6e6a1e97886
Create Date: 2026-03-01 20:51:53.719051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea0e6a19990'
down_revision = 'e6e6a1e97886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Drop leftover temp table from a previous failed batch_alter (SQLite)
    conn.execute(sa.text("DROP TABLE IF EXISTS _alembic_tmp_red_task"))
    has_project_id = any(
        row[1] == 'project_id'
        for row in conn.execute(sa.text("PRAGMA table_info(red_task)")).fetchall()
    )
    if not has_project_id:
        with op.batch_alter_table('red_task', schema=None) as batch_op:
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_red_task_project_id', 'project', ['project_id'], ['id'])

    if not conn.execute(sa.text("SELECT 1 FROM sqlite_master WHERE type='table' AND name='vehicle_move_without_task'")).scalar():
        op.create_table('vehicle_move_without_task',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('move_date', sa.Date(), nullable=False),
            sa.Column('district_id', sa.Integer(), nullable=True),
            sa.Column('project_id', sa.Integer(), nullable=True),
            sa.Column('vehicle_id', sa.Integer(), nullable=True),
            sa.Column('km_in', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('km_out', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('d_km', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('logbook_task', sa.Integer(), nullable=True),
            sa.Column('emg_task', sa.Integer(), nullable=True),
            sa.Column('t_km', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('remarks', sa.Text(), nullable=True),
            sa.Column('fine', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
            sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
            sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_move_without_task')

    with op.batch_alter_table('red_task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_red_task_project_id', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
