"""Add cnic_front_back and license_front_back paths to driver

Revision ID: 3498c269d73b
Revises: g9h0i1j2k3l4
Create Date: 2026-03-18 19:48:18.083811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3498c269d73b'
down_revision = 'g9h0i1j2k3l4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_account_type'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic_front_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cnic_back_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('license_front_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('license_back_path', sa.String(length=500), nullable=True))
        batch_op.alter_column('photo_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('document_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_driver_cnic_no'))
        batch_op.drop_index(batch_op.f('ix_driver_district'))
        batch_op.drop_index(batch_op.f('ix_driver_license_no'))
        batch_op.drop_index(batch_op.f('ix_driver_status'))
        batch_op.create_index(batch_op.f('ix_driver_driver_district'), ['driver_district'], unique=False)

    with op.batch_alter_table('driver_attendance', schema=None) as batch_op:
        batch_op.alter_column('check_in_latitude',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=8),
               existing_nullable=True)
        batch_op.alter_column('check_in_longitude',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=8),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_driver_attendance_date'))
        batch_op.drop_index(batch_op.f('ix_driver_attendance_driver_id'))
        batch_op.drop_index(batch_op.f('uq_attendance_driver_date'))
        batch_op.create_unique_constraint('uq_attendance_driver_date', ['driver_id', 'attendance_date'])
        batch_op.create_foreign_key(None, 'parking_station', ['parking_station_id'], ['id'])

    with op.batch_alter_table('driver_post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_transfer_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_transfer_transfer_date'), ['transfer_date'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_employee_cnic_no'), sqlite_where=sa.text('cnic_no IS NOT NULL'))
        batch_op.create_unique_constraint(None, ['cnic_no'])

    with op.batch_alter_table('fuel_expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_expense_district_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_expense_fueling_date'))
        batch_op.drop_index(batch_op.f('ix_fuel_expense_project_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_expense_vehicle_id'))

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_project_id'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_capacity'))
        batch_op.drop_index(batch_op.f('ix_parking_create_date'))
        batch_op.drop_index(batch_op.f('ix_parking_district'))
        batch_op.drop_index(batch_op.f('ix_parking_tehsil'))
        batch_op.drop_index(batch_op.f('uq_parking_name_district'))
        batch_op.create_unique_constraint('uq_parking_name_district', ['name', 'district'])
        batch_op.create_index(batch_op.f('ix_parking_station_capacity'), ['capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_station_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_station_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_station_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_station_tehsil'), ['tehsil'], unique=False)

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_party_name_type'))
        batch_op.create_unique_constraint('uq_party_name_type', ['name', 'party_type'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_product_name'))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_project_name'))
        batch_op.create_index(batch_op.f('ix_project_assign_date'), ['assign_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)

    with op.batch_alter_table('project_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_transfer_transfer_date'), ['transfer_date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_type'))
        batch_op.drop_index(batch_op.f('uq_vehicle_chassis_no'), sqlite_where=sa.text("chassis_no IS NOT NULL AND chassis_no != ''"))
        batch_op.drop_index(batch_op.f('uq_vehicle_engine_no'), sqlite_where=sa.text("engine_no IS NOT NULL AND engine_no != ''"))
        batch_op.create_index(batch_op.f('ix_vehicle_assign_to_district_date'), ['assign_to_district_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_parking_assign_date'), ['parking_assign_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_vehicle_no'), ['vehicle_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicle_vehicle_type'), ['vehicle_type'], unique=False)
        batch_op.create_unique_constraint(None, ['chassis_no'])
        batch_op.create_unique_constraint(None, ['engine_no'])

    with op.batch_alter_table('vehicle_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_transfer_transfer_date'), ['transfer_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_transfer_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_transfer_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_transfer_transfer_date'))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_vehicle_vehicle_type'))
        batch_op.drop_index(batch_op.f('ix_vehicle_vehicle_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_parking_assign_date'))
        batch_op.drop_index(batch_op.f('ix_vehicle_assign_to_district_date'))
        batch_op.create_index(batch_op.f('uq_vehicle_engine_no'), ['engine_no'], unique=1, sqlite_where=sa.text("engine_no IS NOT NULL AND engine_no != ''"))
        batch_op.create_index(batch_op.f('uq_vehicle_chassis_no'), ['chassis_no'], unique=1, sqlite_where=sa.text("chassis_no IS NOT NULL AND chassis_no != ''"))
        batch_op.create_index(batch_op.f('ix_vehicle_type'), ['vehicle_type'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('project_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_transfer_transfer_date'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_assign_date'))
        batch_op.create_index(batch_op.f('uq_project_name'), ['name'], unique=1)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_product_name'), ['name'], unique=1)

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_constraint('uq_party_name_type', type_='unique')
        batch_op.create_index(batch_op.f('uq_party_name_type'), ['name', 'party_type'], unique=1)

    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_station_tehsil'))
        batch_op.drop_index(batch_op.f('ix_parking_station_name'))
        batch_op.drop_index(batch_op.f('ix_parking_station_district'))
        batch_op.drop_index(batch_op.f('ix_parking_station_create_date'))
        batch_op.drop_index(batch_op.f('ix_parking_station_capacity'))
        batch_op.drop_constraint('uq_parking_name_district', type_='unique')
        batch_op.create_index(batch_op.f('uq_parking_name_district'), ['name', 'district'], unique=1)
        batch_op.create_index(batch_op.f('ix_parking_tehsil'), ['tehsil'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_capacity'), ['capacity'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_type'), ['entry_type'], unique=False)

    with op.batch_alter_table('fuel_expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_expense_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_expense_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_expense_fueling_date'), ['fueling_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_expense_district_id'), ['district_id'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_employee_cnic_no'), ['cnic_no'], unique=1, sqlite_where=sa.text('cnic_no IS NOT NULL'))

    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_transfer_transfer_date'))
        batch_op.drop_index(batch_op.f('ix_driver_transfer_driver_id'))

    with op.batch_alter_table('driver_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('driver_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_attendance_driver_date', type_='unique')
        batch_op.create_index(batch_op.f('uq_attendance_driver_date'), ['driver_id', 'attendance_date'], unique=1)
        batch_op.create_index(batch_op.f('ix_driver_attendance_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_attendance_date'), ['attendance_date'], unique=False)
        batch_op.alter_column('check_in_longitude',
               existing_type=sa.Numeric(precision=12, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('check_in_latitude',
               existing_type=sa.Numeric(precision=12, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_driver_district'))
        batch_op.create_index(batch_op.f('ix_driver_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_license_no'), ['license_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_district'), ['driver_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_cnic_no'), ['cnic_no'], unique=False)
        batch_op.alter_column('document_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('photo_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('license_back_path')
        batch_op.drop_column('license_front_path')
        batch_op.drop_column('cnic_back_path')
        batch_op.drop_column('cnic_front_path')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_account_type'), ['account_type'], unique=False)

    # ### end Alembic commands ###
