"""add employee cnic

Revision ID: 4b18954691fa
Revises: a6d22ae14817
Create Date: 2026-03-05 16:35:50.118065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b18954691fa'
down_revision = 'a6d22ae14817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('cnic_no')

    # ### end Alembic commands ###
