"""Add indexes on sortable columns for performance

Revision ID: 6a89ca3989e1
Revises: c8bed50ba45c
Create Date: 2026-03-13 00:43:09.078010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a89ca3989e1'
down_revision = 'c8bed50ba45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=True)

    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_name'), ['name'], unique=True)

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_assign_date'), ['assign_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_name'), ['name'], unique=False)

    # Skip driver_attendance and driver_post foreign key changes

    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_transfer_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_transfer_transfer_date'), ['transfer_date'], unique=False)

    # Skip notification and user table changes
    
    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_station_name'), ['name'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assign_date'), ['assign_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)

    with op.batch_alter_table('project_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_transfer_transfer_date'), ['transfer_date'], unique=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_assign_to_district_date'), ['assign_to_district_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_parking_assign_date'), ['parking_assign_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_vehicle_no'), ['vehicle_no'], unique=True)

    with op.batch_alter_table('vehicle_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_transfer_transfer_date'), ['transfer_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_transfer_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_transfer_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_transfer_transfer_date'))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_vehicle_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_parking_assign_date'))
        batch_op.drop_index(batch_op.f('ix_vehicle_assign_to_district_date'))

    with op.batch_alter_table('project_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_transfer_transfer_date'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_assign_date'))

    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_station_name'))

    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_transfer_transfer_date'))
        batch_op.drop_index(batch_op.f('ix_driver_transfer_driver_id'))

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_name'))
        batch_op.drop_index(batch_op.f('ix_driver_assign_date'))

    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_name'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_name'))

    # ### end Alembic commands ###
