"""add parking lat long

Revision ID: 6ed65301b315
Revises: a8b9c0d1e2f3
Create Date: 2026-03-05 14:47:07.001773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed65301b315'
down_revision = 'a8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_expense_item', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_station', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('oil_expense_item', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###
