"""add vehicle document_path and driver photo_path document_path

Revision ID: 77d916675066
Revises: 97cbd338b00f
Create Date: 2026-03-01 21:40:14.449302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d916675066'
down_revision = '97cbd338b00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('document_path')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('document_path')
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
