"""Add driver_id to PenaltyRecord

Revision ID: 97cbd338b00f
Revises: 1ea0e6a19990
Create Date: 2026-03-01 21:05:33.960607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cbd338b00f'
down_revision = '1ea0e6a19990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalty_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_penalty_record_driver_id', 'driver', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalty_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_penalty_record_driver_id', type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
