"""extend employee fields

Revision ID: a6d22ae14817
Revises: df9c18d3b466
Create Date: 2026-03-05 16:11:43.347693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d22ae14817'
down_revision = 'df9c18d3b466'
branch_labels = None
depends_on = None


def upgrade():
    # Add extra employee columns only if they don't already exist (safe for existing DBs).
    bind = op.get_bind()
    insp = sa.inspect(bind)
    cols = {c['name'] for c in insp.get_columns('employee')}

    with op.batch_alter_table('employee', schema=None) as batch_op:
        if 'father_name' not in cols:
            batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=True))
        if 'place_of_birth' not in cols:
            batch_op.add_column(sa.Column('place_of_birth', sa.String(length=100), nullable=True))
        if 'dob' not in cols:
            batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        if 'education' not in cols:
            batch_op.add_column(sa.Column('education', sa.String(length=50), nullable=True))
        if 'marital_status' not in cols:
            batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        if 'district' not in cols:
            batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        if 'address' not in cols:
            batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        if 'bank_name' not in cols:
            batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        if 'account_no' not in cols:
            batch_op.add_column(sa.Column('account_no', sa.String(length=50), nullable=True))
        if 'account_title' not in cols:
            batch_op.add_column(sa.Column('account_title', sa.String(length=100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('account_title')
        batch_op.drop_column('account_no')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('address')
        batch_op.drop_column('district')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('education')
        batch_op.drop_column('dob')
        batch_op.drop_column('place_of_birth')
        batch_op.drop_column('father_name')

    # ### end Alembic commands ###
