"""add employee post full name

Revision ID: df9c18d3b466
Revises: 6ed65301b315
Create Date: 2026-03-05 15:52:09.596497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c18d3b466'
down_revision = '6ed65301b315'
branch_labels = None
depends_on = None


def upgrade():
    # Add full_name column to driver_post only if it does not already exist.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    cols = [c['name'] for c in insp.get_columns('driver_post')]
    if 'full_name' in cols:
        return

    with op.batch_alter_table('driver_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_post', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
