"""add task report tables

Revision ID: e6e6a1e97886
Revises: ee5823f584c4
Create Date: 2026-03-01 20:02:18.799646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e6a1e97886'
down_revision = 'ee5823f584c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_status_change', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.alter_column('new_district_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_transfer', schema=None) as batch_op:
        batch_op.alter_column('new_district_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('driver_status_change', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
